# Generated by Django 4.0.4 on 2022-05-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deployer',
            field=models.BooleanField(default=False, verbose_name='deployer status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_dpc',
            field=models.BooleanField(default=False, verbose_name='dpc status'),
        ),
    ]
