# Generated by Django 4.0.4 on 2022-05-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_deployer_user_is_dpc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dep_id',
            field=models.IntegerField(default=False, verbose_name='deployer Id'),
        ),
    ]
