# Generated by Django 4.0.4 on 2022-05-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployment_programs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deploymentprogram',
            old_name='locationId',
            new_name='location_id',
        ),
    ]
