# Generated by Django 4.0.4 on 2022-05-20 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployment_programs', '0002_rename_locationid_deploymentprogram_location_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deploymentprogram',
            old_name='location_id',
            new_name='location',
        ),
    ]
