# Generated by Django 4.0.4 on 2022-05-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployer',
            name='cac_exp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deployer',
            name='dent_exp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deployer',
            name='dent_scheduled',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deployer',
            name='loa_exp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deployer',
            name='med_exp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deployer',
            name='med_requested',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deployer',
            name='med_scheduled',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deployer',
            name='pass_exp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deployer',
            name='visa_exp',
            field=models.DateField(),
        ),
    ]
