# Generated by Django 4.0.4 on 2022-05-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployers', '0002_alter_deployer_cac_exp_alter_deployer_dent_exp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployer',
            name='first_name',
            field=models.CharField(default='fname', max_length=50),
        ),
        migrations.AddField(
            model_name='deployer',
            name='last_name',
            field=models.CharField(default='fname', max_length=50),
        ),
    ]
