# Generated by Django 4.0.4 on 2022-05-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployers', '0003_deployer_first_name_deployer_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployer',
            name='user',
        ),
    ]
