# Generated by Django 4.0.4 on 2022-05-20 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbts', '0002_alter_cbt_exp'),
        ('deployers', '0004_remove_deployer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployer',
            name='cbts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cbts.cbt'),
        ),
        migrations.AlterField(
            model_name='deployer',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
