# Generated by Django 4.0.4 on 2022-05-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployers', '0006_remove_deployer_cbts_deployer_deployment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployer',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deployer',
            name='cac_exp',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='deployer',
            name='dent_exp',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='deployer',
            name='dent_scheduled',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='deployer',
            name='loa_exp',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='deployer',
            name='med_exp',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='deployer',
            name='med_requested',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='deployer',
            name='med_scheduled',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='deployer',
            name='pass_exp',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='deployer',
            name='pass_num',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deployer',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='deployer',
            name='visa_exp',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='deployer',
            name='visa_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deployer',
            name='visa_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
