# Generated by Django 4.0.4 on 2022-05-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployers', '0007_alter_deployer_address_alter_deployer_cac_exp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployer',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
