# Generated by Django 4.0.4 on 2022-05-24 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_remove_requirement_step_requirement_requirement_list'),
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='requirement_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='requirements.requirement'),
            preserve_default=False,
        ),
    ]
