# Generated by Django 4.0.4 on 2022-05-24 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0002_step_requirement_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='requirement_id',
            new_name='requirement',
        ),
    ]
