# Generated by Django 4.0.4 on 2022-05-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0003_rename_requirement_id_step_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
