# Generated by Django 4.0.4 on 2022-05-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0004_step_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='length',
            new_name='len',
        ),
    ]
