# Generated by Django 4.0.4 on 2022-06-02 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('steps', '0005_rename_length_step_len'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_message', models.CharField(max_length=255)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steps.step')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
