# Generated by Django 4.0.4 on 2022-05-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbt',
            name='exp',
            field=models.DateField(),
        ),
    ]
