# Generated by Django 4.0.4 on 2022-05-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_rename_deployment_id_location_deployment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='deployment',
        ),
    ]
