# Generated by Django 4.0.4 on 2022-05-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements_lists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirementlist',
            old_name='requirementId',
            new_name='requirement_id',
        ),
    ]
