# Generated by Django 4.0.4 on 2022-05-20 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements_lists', '0002_rename_requirementid_requirementlist_requirement_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirementlist',
            old_name='requirement_id',
            new_name='requirement',
        ),
    ]
