# Generated by Django 4.0.4 on 2022-06-01 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements_lists', '0004_remove_requirementlist_requirement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementlist',
            name='deployment',
        ),
    ]
