# Generated by Django 4.0.4 on 2022-05-24 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirements_lists', '0004_remove_requirementlist_requirement_and_more'),
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='step',
        ),
        migrations.AddField(
            model_name='requirement',
            name='requirement_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='requirements_lists.requirementlist'),
            preserve_default=False,
        ),
    ]
