# Generated by Django 4.0.4 on 2022-05-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_remove_requirement_step_requirement_requirement_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='dependency',
            new_name='priority',
        ),
    ]
