# Generated by Django 4.0.4 on 2022-06-02 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0003_rename_dependency_requirement_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='priority',
            new_name='dependency',
        ),
    ]
