# Generated by Django 4.0.4 on 2022-05-19 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requirements_lists', '0001_initial'),
        ('deployers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('startDate', models.IntegerField()),
                ('endDate', models.IntegerField()),
                ('deployerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployers.deployer')),
                ('requirementListId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements_lists.requirementlist')),
            ],
        ),
    ]
