# Generated by Django 4.0.4 on 2022-05-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_rename_deployerid_deployment_deployer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='start_date',
            field=models.DateField(),
        ),
    ]
