# Generated by Django 4.0.4 on 2022-05-24 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_remove_location_deployment'),
        ('deployments', '0004_rename_deployer_id_deployment_deployer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='deployer',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='requirement_list',
        ),
        migrations.AddField(
            model_name='deployment',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
            preserve_default=False,
        ),
    ]
