# Generated by Django 4.0.4 on 2022-06-01 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirements_lists', '0005_remove_requirementlist_deployment'),
        ('deployments', '0005_remove_deployment_deployer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='requirement_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='requirements_lists.requirementlist'),
            preserve_default=False,
        ),
    ]
