# Generated by Django 4.0.4 on 2022-05-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentMessage',
            new_name='comment_message',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='stepId',
            new_name='step_id',
        ),
    ]
