# Generated by Django 4.0.4 on 2022-05-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_commentmessage_comment_comment_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='step_id',
            new_name='step',
        ),
    ]
