# Generated by Django 4.0.4 on 2022-05-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_rename_step_id_comment_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='step',
        ),
        migrations.AddField(
            model_name='comment',
            name='step_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
